name: workflow-test

on:
  push:
    branches:
      - develop   # branche qui déclenche le workflow

jobs:
  example-job:           # nom du job
    runs-on: ubuntu-latest   # runner Linux
    container:
      image: node:20         # Docker avec Node.js

    steps:
      
      - name: Test
        run: echo "test vrai"
